---
title: "Schedule"
---

Please read the specified sections *before* class that day. 

<div class="past">
</div> <!--closing "past" div-->


<div class="row">
  <div class="col-md-3">
#### Mon, Jan 4
+ Introduction to the course
+ [Short experiment](https://smithcollege.qualtrics.com/jfe/form/SV_71nqdhEpN8frd6B)
+ Evening session: Optional office hours time
+ Homework:
    + HW #1a: record your name on Moodle
    + HW #1b: CITI training
  </div>
  
  <div class="col-md-3">
#### Tue, Jan 5
+ Four basic designs
+ Homework due today:
    + Read Ch. 1.1-1.2
    + [Remembering George Cobb](https://magazine.amstat.org/blog/2020/07/01/remembering-george-cobb-1947-2020/)
  </div>
  
  <div class="col-md-3">
#### Wed, Jan 6
+ Four basic designs (cont.)
+ Evening session: **MP1**
+ Homework due today:
    + Read Ch. 1.3 + Appendix
    + [Fisher's history of racism](https://en.wikipedia.org/wiki/Ronald_Fisher#Eugenics); [Daniela Witten's tweet starting the conversation to rename Fisher Lectureship](https://twitter.com/daniela_witten/status/1268392721275744256?s=09)
  </div>
  
  <div class="col-md-3">
#### Thurs, Jan 7
+ Informal ANOVA
+ The Fisher assumptions
+ Homework due today:
    + Read Ch. 2.1-2.2
    + **HW #1a and #1b due today at 11:55p**
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Mon, Jan 11
+ Informal ANOVA (cont.)
+ Evening session: Optional office hours time
+ Homework due today:
  + Read Ch. 2.3 
  + Read [How to spot good Covid-19 vaccine trials results when you see them](https://www.statnews.com/2020/11/10/spot-good-covid-19-vaccine-trials-results-when-you-see-them/)
  </div>
  
  <div class="col-md-3">
#### Tue, Jan 12
+ Formal ANOVA 
+ Homework due today:
    + [**HW #2 due today at 9:20a**](intro_to_r.html)
    + Read Ch 3.1-3.3
  </div>
  
  <div class="col-md-3">
#### Wed, Jan 13
+ Formal ANOVA (cont.) 
+ Hypothesis tests and confidence intervals 
+ Evening session: **MP1**
+ Homework due today:
    + Read Ch 3.4-3.5 + Appendix 1
  </div>
  
  <div class="col-md-3">
#### Thurs, Jan 14
+ BF[1] design
+ Homework due today:
  + **HW #3 due on today at 11:55p**
  + Read 5.1-5.2
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Mon, Jan 18
+ **NO CLASS - MLK day**
  </div>
  
  <div class="col-md-3">
#### Tue, Jan 19
+ MP1 Data Collection
+ Analysis of the BF[1] Design in R
+ Factorial crossing and the BF[2] design
+ Homework due today:
    + Read 5.3-5.4, 5.6
    + Read Ch 6.1-6.2 
    + **Mini Project 1 due Thursday morning** (upload to Moodle by Midnight)
    + [**HW #4 due today at 9:20a**](labs/homework3.html)
    
  </div>
  
  <div class="col-md-3">
#### Wed, Jan 20
+ Formal ANOVA of the BF[2]
+ Analysis of the BF[2] Design in R
+ Evening session: **MP1**
+ Homework due today:
    + Read Ch 6.3, 6.5 (optional)
  </div>
  
  <div class="col-md-3">
#### Thurs, Jan 21
- Mini project presentations
+ **Quiz 1 HANDED OUT**
+ Homework due today:
    + **MP1 Due Today at 9:20a**
    + **HW #5 due thurs at 11:55p**
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Mon, Jan 25
+ Blocking and the CB[1] design 
+ Evening session: **MP2**
+ Homework due today:
    + Read Ch 7.1
  </div>
  
  <div class="col-md-3">
#### Tue, Jan 26
+ Blocking and the CB[1] design (cont.)
+ Homework due today:
    + Work on quiz
    + [**HW #6 due today at 9:20a**](labs/homework5.html)
  </div>
  
  <div class="col-md-3">
#### Wed, Jan 27
+ Latin Square design
+ Evening session: **MP2**
+ Homework due today:
    + Read Ch 7.2
  </div>
  
  <div class="col-md-3">
#### Thurs, Jan 28
+ The Split Plot/Repeated Measures design
+ Homework due today:
    + **Quiz 1 DUE TODAY at 11:55p**
    + Read Ch 7.3
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Mon, Feb 1
+ The Split Plot/Repeated Measures design (cont.)
+ Scatterplots for data sets with blocks 
+ Evening session: **MP2**
+ Homework due today:
    + Read Ch. 7.4-7.5
  </div>
  
  <div class="col-md-3">
#### Tue, Feb 2
+ Extending the basic designs
+ Homework due today:
    + Read Ch 9.1-9.2
    + [**HW #7 due today at 9:20a**](homework.html)
  </div>
  
  <div class="col-md-3">
#### Wed, Feb 3
+ Extending the basic designs (cont.)
+ BF[3+] Designs
+ Evening session: **MP2**
+ Homework due today:
    + Read Ch 9.3-9.5
  </div>
  
  <div class="col-md-3">
#### Thurs, Feb 4
+ Multiple Comparisons
+ **Quiz 2 HANDED OUT**
+ Homework due today:
    + Read Ch. 11.1-11.2
    + **HW #8 due thurs at 11:55p**
  </div>
</div>

***

<div class="row">
  <div class="col-md-3">
#### Mon, Feb 8
+ Visualizing 3-factor interactions
+ Compound within-blocks factors
+ Homework due today:
    + Read Ch 9.5 (review sectin 9.3)
  </div>
  
  <div class="col-md-3">
#### Tue, Feb 9
+ Presentations
+ Homework due today:
    + [**HW #9 due today at 9:20a**](labs/homework9.html)
  </div>
  
  <div class="col-md-3">
#### Wed, Feb 10
+ Presentations
+ Homework due today:
  </div>
  
  <div class="col-md-3">
#### Thurs, Feb 11
+ Presentations
+ Homework due today:
    + **MP2 Due Today at 9:20a**
    + **Quiz 2 DUE TODAY at 11:55p**

  </div>
</div>


    